version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "APIGatewayOAuthIntergration-EXAMPLE"
s3_bucket = "some-bucket-to-store-code"
s3_prefix = "APIGatewayOAuthIntergration-EXAMPLE"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
